<a href="https://colab.research.google.com/github/Shreya6503/Development-of-AI-Response-Validation-System-with-Hallucination-Detection-Assistance/blob/main/Task1_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import sqlite3
import pandas as pd

# Create an in-memory SQLite database
conn = sqlite3.connect(":memory:")

cursor = conn.cursor()

print("Database connected successfully!")

Database connected successfully!

In [2]:

cursor.executescript("""
CREATE TABLE Departments (
    dept_id INTEGER PRIMARY KEY,
    dept_name TEXT
);

CREATE TABLE Employees (
    emp_id INTEGER PRIMARY KEY,
    emp_name TEXT,
    department_id INTEGER,
    salary INTEGER,
    city TEXT
);

INSERT INTO Departments VALUES
(1, 'IT'),
(2, 'HR'),
(3, 'Finance'),
(4, 'Marketing');

INSERT INTO Employees VALUES
(101, 'Amit', 1, 60000, 'Pune'),
(102, 'Priya', 2, 45000, 'Mumbai'),
(103, 'Rahul', 1, 75000, 'Pune'),
(104, 'Sneha', 3, 55000, 'Delhi'),
(105, 'Karan', 1, 80000, 'Bangalore'),
(106, 'Neha', 2, 50000, 'Pune'),
(107, 'Rohit', 3, 65000, 'Mumbai'),
(108, 'Anjali', 4, 40000, 'Delhi'),
(109, 'Vikas', 1, 75000, 'Mumbai'),
(110, 'Pooja', 4, 48000, 'Pune');
""")

conn.commit()

print("Tables created and data inserted successfully!")

Tables created and data inserted successfully!

In [3]:
def run_query(query):
    return pd.read_sql_query(query, conn)

print("SQL query function is ready!")

SQL query function is ready!

Question 1: Retrieve All Records from a Table.

Prompt: Write an SQL query to display all employee records from the Employees table.

In [4]:
run_query("SELECT * FROM Employees ORDER BY emp_id;")

   emp_id emp_name  department_id  salary       city
0     101     Amit              1   60000       Pune
1     102    Priya              2   45000     Mumbai
2     103    Rahul              1   75000       Pune
3     104    Sneha              3   55000      Delhi
4     105    Karan              1   80000  Bangalore
5     106     Neha              2   50000       Pune
6     107    Rohit              3   65000     Mumbai
7     108   Anjali              4   40000      Delhi
8     109    Vikas              1   75000     Mumbai
9     110    Pooja              4   48000       Pune

Question 2: Retrieve Specific Columns.

Prompt: Write an SQL query to display only the names and salaries of all employees.

In [5]:
run_query("""SELECT emp_name, salary
FROM Employees
ORDER BY emp_id;""")

  emp_name  salary
0     Amit   60000
1    Priya   45000
2    Rahul   75000
3    Sneha   55000
4    Karan   80000
5     Neha   50000
6    Rohit   65000
7   Anjali   40000
8    Vikas   75000
9    Pooja   48000

Question 3: Find Employees Earning More Than 60,000.

Prompt: Write an SQL query to display employees whose salary is greater than 60,000.

In [6]:
run_query("""
SELECT emp_name, salary
FROM Employees
WHERE salary > 60000
ORDER BY salary DESC, emp_name;"""
)

  emp_name  salary
0    Karan   80000
1    Rahul   75000
2    Vikas   75000
3    Rohit   65000

Question 4: Find Employees Working in Pune.

Prompt: Write an SQL query to retrieve the names and cities of employees who work in Pune.

In [7]:
run_query("""
SELECT emp_name, city
FROM Employees
WHERE city = 'Pune'
ORDER BY emp_id;
""" )

  emp_name  city
0     Amit  Pune
1    Rahul  Pune
2     Neha  Pune
3    Pooja  Pune

Question 5: Sort Employees by Salary in Descending Order.

Prompt: Write an SQL query to display employees sorted by salary from highest to lowest.

In [8]:
run_query(("""
SELECT emp_name, salary
FROM Employees
ORDER BY salary DESC, emp_id;
"""))

  emp_name  salary
0    Karan   80000
1    Rahul   75000
2    Vikas   75000
3    Rohit   65000
4     Amit   60000
5    Sneha   55000
6     Neha   50000
7    Pooja   48000
8    Priya   45000
9   Anjali   40000

Question 6: Find Employees Whose Salary Is Between 50,000 and 75,000.

Prompt: Write an SQL query to retrieve employees earning between 50,000 and 75,000, inclusive.

In [9]:
run_query("""
SELECT emp_name, salary
FROM Employees
WHERE salary BETWEEN 50000 AND 75000
ORDER BY salary, emp_id;
""")

  emp_name  salary
0     Neha   50000
1    Sneha   55000
2     Amit   60000
3    Rohit   65000
4    Rahul   75000
5    Vikas   75000

Question 7: Find Employees Whose Names Start with 'A'.

Prompt: Write an SQL query to find employees whose names begin with the letter A using the LIKE operator.

In [10]:
run_query("""
SELECT emp_name
FROM Employees
WHERE emp_name LIKE 'A%'
ORDER BY emp_id;
""")

  emp_name
0     Amit
1   Anjali

% represents zero or more characters in SQL pattern matching.

Question 8: Find Employees Working in Multiple Cities.

Prompt: Write an SQL query to find employees working in either Pune or Mumbai using the IN operator.

In [11]:
run_query("""
SELECT emp_name, city
FROM Employees
WHERE city IN ('Pune', 'Mumbai')
ORDER BY emp_id;
""")

  emp_name    city
0     Amit    Pune
1    Priya  Mumbai
2    Rahul    Pune
3     Neha    Pune
4    Rohit  Mumbai
5    Vikas  Mumbai
6    Pooja    Pune

Question 9: Display Unique Employee Cities.

Prompt: Write an SQL query to display all unique cities where employees work using the DISTINCT keyword.

In [12]:
run_query("""
SELECT DISTINCT city
FROM Employees
ORDER BY city;
""")

        city
0  Bangalore
1      Delhi
2     Mumbai
3       Pune

Question 11: Count the Total Number of Employees.

Prompt: Write an SQL query to find the total number of employees working in the company using the COUNT() function.

In [13]:
run_query("""
SELECT COUNT(*) AS total_employees
FROM Employees;
""")

   total_employees
0               10

Question 12: Find the Total and Average Salary of Employees.

Prompt: Write an SQL query to calculate the total salary expenditure and average employee salary using SUM() and AVG().

In [14]:
run_query("""
SELECT
    SUM(salary) AS total_salary,
    AVG(salary) AS average_salary
FROM Employees;
""")

   total_salary  average_salary
0        593000         59300.0

Question 13: Find the Highest and Lowest Employee Salaries.

Prompt: Write an SQL query to display the maximum and minimum salaries among all employees using MAX() and MIN().

In [16]:
run_query("""
SELECT
    MAX(salary) AS highest_salary,
    MIN(salary) AS lowest_salary
FROM Employees;
""")

   highest_salary  lowest_salary
0           80000          40000

Question 14: Count Employees in Each Department.

Prompt: Write an SQL query to display each department name and the number of employees working in that department using GROUP BY.

In [17]:
run_query("""
SELECT
    d.dept_name,
    COUNT(e.emp_id) AS employee_count
FROM Departments d
LEFT JOIN Employees e
    ON d.dept_id = e.department_id
GROUP BY d.dept_id, d.dept_name
ORDER BY d.dept_id;
""")

   dept_name  employee_count
0         IT               4
1         HR               2
2    Finance               2
3  Marketing               2

GROUP BY combines rows having the same values into groups. Here, LEFT JOIN also ensures that departments with zero employees would appear with a count of 0.

Question 15: Find Departments Having an Average Salary Greater Than 55,000.

Prompt: Write an SQL query to display departments whose average employee salary is greater than 55,000 using GROUP BY and HAVING.

In [18]:
run_query("""

SELECT
    d.dept_name,
    AVG(e.salary) AS average_salary
FROM Employees e
JOIN Departments d
    ON e.department_id = d.dept_id
GROUP BY d.dept_id, d.dept_name
HAVING AVG(e.salary) > 55000
ORDER BY average_salary DESC;
""")

  dept_name  average_salary
0        IT         72500.0
1   Finance         60000.0

WHERE filters individual rows before grouping, while HAVING filters groups after aggregation.

Question 16: Display Employee Names with Department Names Using INNER JOIN
Prompt: Write an SQL query to display employee names along with their department names using INNER JOIN.

In [19]:
run_query("""
SELECT
    e.emp_name,
    d.dept_name
FROM Employees e
INNER JOIN Departments d
    ON e.department_id = d.dept_id
ORDER BY e.emp_id;
""")

  emp_name  dept_name
0     Amit         IT
1    Priya         HR
2    Rahul         IT
3    Sneha    Finance
4    Karan         IT
5     Neha         HR
6    Rohit    Finance
7   Anjali  Marketing
8    Vikas         IT
9    Pooja  Marketing

INNER JOIN returns only rows that have matching values in both tables.

Question 17: Display All Employees Using LEFT JOIN.

Prompt: Write an SQL query to display all employees along with their department names using LEFT JOIN, including employees who may not be assigned to a department.

In [21]:
run_query("""
SELECT
    e.emp_name,
    d.dept_name
FROM Employees e
LEFT JOIN Departments d
    ON e.department_id = d.dept_id
ORDER BY e.emp_id;
""")

  emp_name  dept_name
0     Amit         IT
1    Priya         HR
2    Rahul         IT
3    Sneha    Finance
4    Karan         IT
5     Neha         HR
6    Rohit    Finance
7   Anjali  Marketing
8    Vikas         IT
9    Pooja  Marketing

LEFT JOIN returns all rows from the left table and matching rows from the right table. When no match exists, the right-table columns contain NULL.

In [23]:
run_query("""
SELECT
    d.dept_name,
    e.emp_name
FROM Departments d
LEFT JOIN Employees e
    ON d.dept_id = e.department_id
ORDER BY d.dept_id, e.emp_id;
""")

   dept_name emp_name
0         IT     Amit
1         IT    Rahul
2         IT    Karan
3         IT    Vikas
4         HR    Priya
5         HR     Neha
6    Finance    Sneha
7    Finance    Rohit
8  Marketing   Anjali
9  Marketing    Pooja

RIGHT JOIN returns all rows from the right table and matching rows from the left table.

Question 19: Display All Employees and Departments Using FULL OUTER JOIN.

Prompt: Write an SQL query to display all employees and all departments, including unmatched records from either table, using the concept of FULL OUTER JOIN.

In [24]:
run_query("""
SELECT
    e.emp_name,
    d.dept_name
FROM Employees e
LEFT JOIN Departments d
    ON e.department_id = d.dept_id

UNION ALL

SELECT
    e.emp_name,
    d.dept_name
FROM Departments d
LEFT JOIN Employees e
    ON d.dept_id = e.department_id
WHERE e.emp_id IS NULL

ORDER BY dept_name, emp_name;
""")

  emp_name  dept_name
0    Rohit    Finance
1    Sneha    Finance
2     Neha         HR
3    Priya         HR
4     Amit         IT
5    Karan         IT
6    Rahul         IT
7    Vikas         IT
8   Anjali  Marketing
9    Pooja  Marketing

FULL OUTER JOIN returns matching rows and unmatched rows from both tables.

Question 20: Find Employees Working in the Same Department Using SELF JOIN.

Prompt: Write an SQL query to find pairs of employees who work in the same department. Avoid pairing an employee with themselves and avoid duplicate reversed pairs.

In [25]:
run_query("""
SELECT
    e1.emp_name AS employee_1,
    e2.emp_name AS employee_2,
    d.dept_name
FROM Employees e1
INNER JOIN Employees e2
    ON e1.department_id = e2.department_id
    AND e1.emp_id < e2.emp_id
INNER JOIN Departments d
    ON e1.department_id = d.dept_id
ORDER BY d.dept_id, e1.emp_id, e2.emp_id;
""")

  employee_1 employee_2  dept_name
0       Amit      Rahul         IT
1       Amit      Karan         IT
2       Amit      Vikas         IT
3      Rahul      Karan         IT
4      Rahul      Vikas         IT
5      Karan      Vikas         IT
6      Priya       Neha         HR
7      Sneha      Rohit    Finance
8     Anjali      Pooja  Marketing

Question 21: Find Employees Earning More Than the Average Salary.

Prompt: Write an SQL query to find employees whose salary is greater than the average salary of all employees using a subquery.

In [26]:
run_query("""
SELECT
    emp_name,
    salary
FROM Employees
WHERE salary > (
    SELECT AVG(salary)
    FROM Employees
)
ORDER BY salary DESC, emp_id;
""")

  emp_name  salary
0    Karan   80000
1    Rahul   75000
2    Vikas   75000
3    Rohit   65000
4     Amit   60000

This is a scalar subquery, which returns a single value used in the outer query.

Question 22: Find the Second-Highest Distinct Salary.

Prompt: Write an SQL query to find the second-highest distinct salary from the Employees table without using LIMIT or window functions.

In [27]:
run_query("""
SELECT MAX(salary) AS second_highest_salary
FROM Employees
WHERE salary < (
    SELECT MAX(salary)
    FROM Employees
);
""")

   second_highest_salary
0                  75000

This query finds the second-highest distinct salary, not necessarily the salary of the second employee when salaries are sorted. If fewer than two distinct non-NULL salaries exist, the result is NULL.

Question 23: Find Employees Working in the IT Department Using a Subquery.

Prompt: Write an SQL query to retrieve employees working in the IT department using a subquery instead of a JOIN.

In [28]:
run_query("""
SELECT
    emp_name,
    salary
FROM Employees
WHERE department_id IN (
    SELECT dept_id
    FROM Departments
    WHERE dept_name = 'IT'
)
ORDER BY emp_id;
""")

  emp_name  salary
0     Amit   60000
1    Rahul   75000
2    Karan   80000
3    Vikas   75000

Question 24: Find Employees Earning More Than Their Department's Average Salary.

Prompt: Write an SQL query to find employees whose salaries are greater than the average salary of their respective departments using a correlated subquery.

In [29]:
run_query("""
SELECT
    e.emp_name,
    e.salary,
    d.dept_name
FROM Employees e
JOIN Departments d
    ON e.department_id = d.dept_id
WHERE e.salary > (
    SELECT AVG(e2.salary)
    FROM Employees e2
    WHERE e2.department_id = e.department_id
)
ORDER BY d.dept_id, e.emp_id;
""")

  emp_name  salary  dept_name
0    Rahul   75000         IT
1    Karan   80000         IT
2    Vikas   75000         IT
3     Neha   50000         HR
4    Rohit   65000    Finance
5    Pooja   48000  Marketing

Question 25: Find Departments Having at Least One Employee Earning More Than 70,000.

Prompt: Write an SQL query to find department names where at least one employee earns more than 70,000 using the EXISTS operator.

In [30]:
run_query("""
SELECT
    d.dept_name
FROM Departments d
WHERE EXISTS (
    SELECT 1
    FROM Employees e
    WHERE e.department_id = d.dept_id
      AND e.salary > 70000
)
ORDER BY d.dept_id;
""")

  dept_name
0        IT

EXISTS returns true when the subquery produces at least one row. It is useful for checking whether related records exist without returning duplicates.

What Are SQL Window Functions?

Window functions perform calculations across related rows without combining them into a single row, unlike GROUP BY.

The general syntax is:

FUNCTION_NAME()OVER (

    PARTITION BY column_name
    ORDER BY column_name
)

OVER() defines the window.

PARTITION BY divides rows into groups.

ORDER BY determines the order within each window.

Question 26: Assign Row Numbers to Employees Based on Salary.

Prompt: Write an SQL query to assign a unique row number to each employee based on salary in descending order using ROW_NUMBER().

In [31]:
run_query("""
SELECT
    emp_name,
    salary,
    ROW_NUMBER() OVER (
        ORDER BY salary DESC, emp_id
    ) AS row_num
FROM Employees
ORDER BY row_num;
""")

  emp_name  salary  row_num
0    Karan   80000        1
1    Rahul   75000        2
2    Vikas   75000        3
3    Rohit   65000        4
4     Amit   60000        5
5    Sneha   55000        6
6     Neha   50000        7
7    Pooja   48000        8
8    Priya   45000        9
9   Anjali   40000       10

ROW_NUMBER() assigns a unique sequential number to each row, even when multiple employees have the same salary.

Question 27: Rank Employees by Salary Using RANK().

Prompt: Write an SQL query to rank employees according to their salaries in descending order using RANK(). Employees with equal salaries should receive the same rank.

In [32]:
run_query("""
SELECT
    emp_name,
    salary,
    RANK() OVER (
        ORDER BY salary DESC
    ) AS salary_rank
FROM Employees
ORDER BY salary DESC, emp_id;
""")

  emp_name  salary  salary_rank
0    Karan   80000            1
1    Rahul   75000            2
2    Vikas   75000            2
3    Rohit   65000            4
4     Amit   60000            5
5    Sneha   55000            6
6     Neha   50000            7
7    Pooja   48000            8
8    Priya   45000            9
9   Anjali   40000           10

RANK() assigns the same rank to equal values but skips subsequent ranks. Because two employees have rank 2, the next employee receives rank 4.

Question 28: Rank Employees Using DENSE_RANK().

Prompt: Write an SQL query to assign salary ranks using DENSE_RANK() without skipping ranks when employees have equal salaries.

In [33]:
run_query("""
SELECT
    emp_name,
    salary,
    DENSE_RANK() OVER (
        ORDER BY salary DESC
    ) AS dense_salary_rank
FROM Employees
ORDER BY salary DESC, emp_id;
""")

  emp_name  salary  dense_salary_rank
0    Karan   80000                  1
1    Rahul   75000                  2
2    Vikas   75000                  2
3    Rohit   65000                  3
4     Amit   60000                  4
5    Sneha   55000                  5
6     Neha   50000                  6
7    Pooja   48000                  7
8    Priya   45000                  8
9   Anjali   40000                  9

DENSE_RANK() gives equal values the same rank without gaps. It is useful for finding the second-highest distinct salary.

Question 29: Calculate the Running Total of Employee Salaries.

Prompt: Write an SQL query to calculate the cumulative salary total for employees ordered by employee ID using SUM() as a window function.

In [34]:
run_query("""
SELECT
    emp_name,
    salary,
    SUM(salary) OVER (
        ORDER BY emp_id
        ROWS BETWEEN UNBOUNDED PRECEDING
        AND CURRENT ROW
    ) AS running_total
FROM Employees
ORDER BY emp_id;
""")

  emp_name  salary  running_total
0     Amit   60000          60000
1    Priya   45000         105000
2    Rahul   75000         180000
3    Sneha   55000         235000
4    Karan   80000         315000
5     Neha   50000         365000
6    Rohit   65000         430000
7   Anjali   40000         470000
8    Vikas   75000         545000
9    Pooja   48000         593000

A running total adds the current row's value to the sum of all preceding rows. ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW explicitly defines the cumulative window.

Question 30: Find the Highest-Paid Employee in Each Department.

Prompt: Write an SQL query to find the highest-paid employee in each department using DENSE_RANK() and PARTITION BY. Include all employees tied for the highest salary.

In [35]:
run_query("""
WITH RankedEmployees AS (
    SELECT
        e.emp_name,
        d.dept_name,
        e.salary,
        d.dept_id,
        e.emp_id,
        DENSE_RANK() OVER (
            PARTITION BY e.department_id
            ORDER BY e.salary DESC
        ) AS salary_rank
    FROM Employees e
    JOIN Departments d
        ON e.department_id = d.dept_id
)
SELECT
    emp_name,
    dept_name,
    salary
FROM RankedEmployees
WHERE salary_rank = 1
ORDER BY dept_id, emp_id;
""")

  emp_name  dept_name  salary
0    Karan         IT   80000
1     Neha         HR   50000
2    Rohit    Finance   65000
3    Pooja  Marketing   48000

PARTITION BY restarts the ranking within each department. DENSE_RANK() = 1 returns the highest-paid employee or employees from each department, including ties.

Question 31: Convert Employee Names to Uppercase and Lowercase.

Prompt: Write an SQL query to display employee names in both uppercase and lowercase using the UPPER() and LOWER() functions.

In [36]:
run_query("""
SELECT
    emp_name,
    UPPER(emp_name) AS uppercase_name,
    LOWER(emp_name) AS lowercase_name
FROM Employees
ORDER BY emp_id;
""")

  emp_name uppercase_name lowercase_name
0     Amit           AMIT           amit
1    Priya          PRIYA          priya
2    Rahul          RAHUL          rahul
3    Sneha          SNEHA          sneha
4    Karan          KARAN          karan
5     Neha           NEHA           neha
6    Rohit          ROHIT          rohit
7   Anjali         ANJALI         anjali
8    Vikas          VIKAS          vikas
9    Pooja          POOJA          pooja

UPPER() converts text to uppercase, while LOWER() converts it to lowercase. These functions are commonly used for text formatting and case-insensitive comparisons.

Question 32: Find the Length of Employee Names.

Prompt: Write an SQL query to display employee names along with the number of characters in each name using the LENGTH() function.

In [37]:
run_query("""
SELECT
    emp_name,
    LENGTH(emp_name) AS name_length
FROM Employees
ORDER BY emp_id;
""")

  emp_name  name_length
0     Amit            4
1    Priya            5
2    Rahul            5
3    Sneha            5
4    Karan            5
5     Neha            4
6    Rohit            5
7   Anjali            6
8    Vikas            5
9    Pooja            5

Question 33: Extract the First Three Characters of Employee Names.

Prompt: Write an SQL query to extract the first three characters of each employee's name using the SUBSTR() function.

In [38]:
run_query("""
SELECT
    emp_name,
    SUBSTR(emp_name, 1, 3) AS first_three_characters
FROM Employees
ORDER BY emp_id;
""")

  emp_name first_three_characters
0     Amit                    Ami
1    Priya                    Pri
2    Rahul                    Rah
3    Sneha                    Sne
4    Karan                    Kar
5     Neha                    Neh
6    Rohit                    Roh
7   Anjali                    Anj
8    Vikas                    Vik
9    Pooja                    Poo

SUBSTR(text, start, length) extracts part of a string. In SQLite, the starting position is 1 for the first character.

Question 34: Calculate the Number of Days Between Two Dates.

Prompt: Write an SQL query to calculate the number of days between two given dates using SQLite date functions.
Use the sample dates 2026-01-01 and 2026-01-15.

In [39]:
run_query("""
SELECT
    '2026-01-01' AS start_date,
    '2026-01-15' AS end_date,
    CAST(
        julianday('2026-01-15') -
        julianday('2026-01-01')
        AS INTEGER
    ) AS days_difference;
""")

   start_date    end_date  days_difference
0  2026-01-01  2026-01-15               14

Question 35: Replace NULL Values Using COALESCE().

Prompt: Write an SQL query to display employee names and their department names. If an employee has no matching department, display "Not Assigned" instead of NULL using COALESCE().

In [40]:
run_query("""
SELECT
    e.emp_name,
    COALESCE(d.dept_name, 'Not Assigned') AS department
FROM Employees e
LEFT JOIN Departments d
    ON e.department_id = d.dept_id
ORDER BY e.emp_id;
""")

  emp_name department
0     Amit         IT
1    Priya         HR
2    Rahul         IT
3    Sneha    Finance
4    Karan         IT
5     Neha         HR
6    Rohit    Finance
7   Anjali  Marketing
8    Vikas         IT
9    Pooja  Marketing

COALESCE() returns the first non-NULL value from its arguments.
Because all employees in the sample data have assigned departments, the output contains no "Not Assigned" values. However, if an employee's department_id is NULL or has no matching department, the query will display "Not Assigned".